#!/usr/bin/env bash
# Script displays content of current directory in list format
# Displays the part of the name after the first dash only

mylist=$(ls)

for i in $mylist; do
  echo "$i" | cut -d '-' -f2
done
